version: '3.8'

services:

  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx2
    ports:
      - "8080:80"
    volumes:
      - ./online_shop_complete:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db

  #Database Service
  # db:
  #   image : mysql
  #   container_name : mysql
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: online_shop
  #     MYSQL_ROOT_PASSWORD: password
  db:
    image: postgres
    container_name: postgres2
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_DB: online_shop2
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: password 

  # Application Service
  app:
    container_name: online_shop2
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./online_shop_complete:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www

  #phpMyAdmin Service
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   ports:
  #     - "3400:80"
  #   depends_on:
  #     - db
  pgadmin2:
    image: dpage/pgadmin4
    container_name: pgAdmin2
    ports:
      - "5050:80"
    depends_on:
      - db 
    environment:
      PGADMIN_DEFAULT_EMAIL: hernandomanotoa@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: password 
